### PR TITLE
Dependencies, conf folder, gitignore

### LINKED ISSUE #2: Fix missing dependencies and folder
When I run `gulp-sonar` I get an error that node couldn't find the module `through2`, because it is missing in your `package.json`.

Also when `gulp-sonar` tries to write its `sonar-runner.properties` it fails miserably because the directory `conf` is missing.

PR will follow.

### PR DESCRIPTION
**Pull request by prayerslayer**
Fixes #2

### CODE REVIEW

**Comment by stramel** [comment]
I think conventions for keeping a folder that is empty is to use either a blank file that is named `.gitkeep` or properly specify the path in the `.gitignore` using the `!` like so, `!/sonar-runner-2.3/conf/`. However, this will check in anything in this folder to the repository.

**Comment by machellerogden** [comment]
Thanks for the PR! Much appreciated. I've added some comments. Please review and let me know if you have any questions or concerns.

**Comment by prayerslayer** [comment]
Thanks for the quick response. I updated the PR accordingly. If it's fine and you'll merge it, I'd ask you to update the npm module as well, because right now it's broken.

Just out of curiosity, why do you prefer to exclude `.gitignore`?

**Comment by machellerogden** [comment]
Thanks for the update. I'll merge it in, bump the version and re-publish to npm, though I probably won't get to the npm publish until tomorrow.

I'm reconsidering my stance on committing the `.gitignore` ... historically, I've `.gitignore`'d my `.gitignore` because it often has entries which are specific to the tools I use, but I suppose it would be a better practice to put these "private" entries into my `.gitconfig`. Considering that, I'll go ahead and commit a `.gitignore` as well.

Thanks again!

**Pull request merged**
